### ISSUE TITLE
Suggestion, use Golang -> Wasm

### ISSUE THREAD

**Issue by jaecktec** [andygeiss/esp32#1]
hey, just stumbled upon your git repository. Have you considered to use https://github.com/wasm3/wasm3 instead of writing your own transpiler? Might be worth a look.

In case you're not interested, just close this and ignore me :)

**Comment by andygeiss** [comment]
Hi,
I started that project 3 years ago with the educational aspect of doing something by myself ;-)
At that time WebAssembly was not there.
Today Igor from Espressif is also contributing to the repository you mentioned earlier.
So I think it should be the standard way to do it, without a doubt.
Thanks
Andy

**Comment by jaecktec** [comment]
Ah okay, didn't pay attention to the timestamp, but cool that you are still active and responding ✌️
